spring:
  application:
    name: dubbo-client

dubbo:
  application:
    name: dubbo-client
    owner: test
  protocol:
    name: dubbo
    port: 9527
  config:
    multiple: false
  registry:
    address: zookeeper://localhost:2182 | zookeeper://localhost:2181
    file: ${user.home}/.dubbo/dubbo-client.properties
