spring:
  application:
    name: dubbo-client

dubbo:
  application:
    name: dubbo-client
    owner: test
  protocol:
    name: dubbo
    port: 9527
  metadata-report:
    address: nacos://127.0.0.1:8848
  registry:
    # 服务注册中心
    address: nacos://127.0.0.1:8848
    # 缓存的服务信息
    file: ${user.home}/.dubbo/dubbo-client.properties
    simplified: true
