spring:
  application:
    name: dubbo-server-sample

dubbo:
  application:
    name: dubbo-server
    owner: test
  protocol:
    name: dubbo
    port: 9527
    dispatcher: message
    threadpool: fixed
    threads: 200
  metadata-report:
    address: nacos://127.0.0.1:8848
  registry:
    # 服务注册中心
    address: nacos://127.0.0.1:8848
    # 缓存的服务信息
    file: ${user.home}/.dubbo/dubbo-server.properties
    simplified: true
